language: nix
sudo: false
env:
  matrix:
    - target=ci-python2
    - target=ci-python3
    - target=ci-ocaml
    # - target=ci-opam
    - target=ci-permutation
notifications:
  email: false
script:
  - make "$target"
